### ISSUE TITLE
Cannot install on HA

### ISSUE THREAD

**Issue by savaspar** [bratanon/lifesos_addon#1]
Tried to install it via Addons samba folder as custom add-on but the installation cannot take place on HA ver. 2022.2.9 with supervisor 2022.01.1 running on Pi. There is the following error during the installation:

The command '/bin/bash -o pipefail -c apk add --no-cache py3-pip python3 && pip install --no-cache-dir --prefer-binary --find-links "https://wheels.home-assistant.io/alpine-3.13/${BUILD_ARCH}/" -r /tmp/requirements.txt' returned a non-zero code: 2

**Comment by bratanon** [comment]
Sorry for late answer, that is because the python version was not set to a fixed one, and this lib requires a lower then the lastest. 

If you still interested, try this again as the new version have fixed version.
