### ISSUE TITLE
Unable to install addon

### ISSUE THREAD

**Issue by snowgumrd** [bratanon/lifesos_addon#2]
Really excited about this option as my current set up seems to throw up random issues and errors that I can't diagnose.

However, I'm having trouble installing this as an addon. I get the error message:

The command '/bin/bash -o pipefail -c apk add --no-cache --virtual .build-dependencies build-base=0.5-r3 linux-headers=6.5-r0 npm=10.2.5-r0 && apk add --no-cache nodejs=20.10.0-r1 yq=4.35.2-r1 && npm install -g nodesos_mqtt@${NODESOS_MQTT_VERSION} && apk del --no-cache --purge .build-dependencies && rm -fr /tmp/*' returned a non-zero code: 4

Please help.

**Comment by bratanon** [comment]
It seems like the yg package is out of date. 

This will be fixed in the upcoming release of this addon.

**Comment by bratanon** [comment]
Try the latest version. 3.1. This issue should be solved with that version.

**Comment by snowgumrd** [comment]
Amazing. It worked! Thank you! I was already contemplating having to look for an updated replacement to an otherwise workable system.
